fidelity/kconnect

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- code-of-conduct.md
- docs/README.md
Added some initial base documentation and template files that
are expected of the repo for OSS.
Relates to: #2, #5, #6
> WIP docs: repo and community documentation

- .github/workflows/labeler.yml
Added GitHub Actions workflow that will add a label to a PR
depending on its size.
Fixes #7
> build: add size labels for PR size

- .goreleaser.yml
Added the `prelease: auto` to the goreleaser configuration so that releases in GitHub are marked as pre-release if there is any indicator after the semver version number.
Fixes #
> chore: added prelease to goreleaser

- pkg/flags/unmarshal.go
- pkg/plugins/discovery/aws/config.go
The CA cert for EKS needs to be base64 decoded
Fixes #
> chore: remove rougue print and CA cert is base 64 decoded

- internal/app/use.go
- internal/commands/use/use.go
- pkg/plugins/discovery/aws/config.go
- pkg/provider/types.go
When a cluster is selected and the kubeconfig is generated there
is now an option to make that context the current by using
the new `--set-current` flag with the `use` command.
Fixes #68
> feat: allow setting current context

- .golangci.yml
- internal/commands/root.go
- internal/commands/use/use.go
- internal/usage/usage.go
- main.go
- pkg/aws/clients.go
- pkg/config/config.go
- pkg/config/unmarshall.go
- pkg/flags/flags.go
- pkg/k8s/kubeconfig/kubeconfig.go
- pkg/plugins/discovery/aws/provider.go
- pkg/plugins/discovery/aws/resolver.go
- pkg/plugins/discovery/plugins.go
- pkg/plugins/identity/empty/empty.go
- pkg/plugins/identity/plugins.go
- pkg/plugins/identity/saml/saml.go
- pkg/plugins/identity/saml/sp/aws/provider.go
- pkg/plugins/identity/saml/sp/aws/resolver.go
- pkg/plugins/identity/saml/sp/aws/resolver_debug.go
- pkg/plugins/identity/saml/sp/aws/resolver_interactive.go
- pkg/plugins/identity/saml/sp/aws/store.go
- pkg/plugins/identity/saml/sp/types.go
- pkg/provider/context.go
- pkg/provider/flags.go
- pkg/provider/registry.go
- pkg/provider/types.go
Removed flags/flagset from leaking through into the providers. Replaced with teh concept of config items and config sets.
Fixes #
> refactor: introduce config set instead of using flagset everywhere

- pkg/plugins/discovery/aws/config.go
> fix: add cluster name to username of kubeconfig

- api/v1alpha1/history_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- go.mod
- internal/app/use.go
- internal/defaults/defaults.go
- pkg/config/configuration.go
- pkg/history/filter.go
- pkg/history/loader/loader.go
- pkg/history/store.go
- pkg/history/store_test.go
- pkg/k8s/kubeconfig/kubeconfig.go
- pkg/plugins/discovery/aws/config.go
- pkg/provider/types.go
Merging of the kubeconfig was failing when the cluster connected to was the same as the previous usage. Additionally duplicate history entries where written for the same connection.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)
Fixes #90 
Fixes #89
> fix: kubeconfig merge and duplicate history entries

- .goreleaser.yml
Make kconnect available as a .deb or .rpm download for use on linux.
Fixes #62
> feat: add deb and rpm packaging

- internal/app/to.go
- internal/commands/configure/configure.go
- internal/commands/ls/ls.go
- internal/commands/to/to.go
- internal/commands/use/use.go
- pkg/flags/flags.go
- pkg/provider/config.go
Changed to propogate setting the current context when using the
`to` command to connect to a previously connected cluster.
Fixes #109
> fix: set current context when using 'to'

- internal/app/config.go
- internal/app/to.go
- internal/app/use.go
- internal/commands/root.go
- pkg/config/configset.go
- pkg/flags/flags.go
The history extension is not being set when using `kconnect use`
Fixes #118
> Set history on use

- internal/commands/configure/configure.go
- internal/commands/ls/ls.go
- internal/commands/to/to.go
- internal/commands/use/use.go
The logging has been changed in the commands so that the logger is created at execution of the command and not when the command is created. This is to make sure the log level is respected.
We need to rethink logging as part of #119 
Fixes #
> refactor: changed the logging in the commands 

- api/v1alpha1/history_types.go
The history table output now includes the username and alias
Fixes #103
> feat: alias and username in table output

- internal/app/config.go
- internal/app/use.go
- internal/commands/configure/configure.go
- internal/commands/ls/ls.go
- internal/commands/root.go
- internal/commands/to/to.go
- internal/commands/use/use.go
- pkg/config/configset.go
- pkg/plugins/discovery/aws/provider.go
- pkg/plugins/identity/saml/saml.go
- pkg/plugins/identity/saml/sp/aws/provider.go
- pkg/plugins/identity/saml/sp/aws/resolver.go
- pkg/plugins/identity/saml/sp/types.go
- pkg/provider/config.go
The AWS profile name is now auto-created and this stops the sharing of credentials between subsequent calls to the kconnect which caused issues.
Also, changed how config values are persisted to history as role-arn wasn't being peristsed
Fixes #126 
Fixes #108
> fix: removed re-using cached credentials

- internal/app/use.go
- internal/commands/use/use.go
- pkg/plugins/discovery/aws/config.go
- pkg/provider/types.go
Add namespace as a param to `use` command to set in current context.
Fixes #104
> feat: set namespace in kubeconfig

- Makefile
- api/v1alpha1/history_types.go
- api/v1alpha1/history_types_internal_test.go
- docs/book/src/commands/ls.md
- docs/book/src/commands/use_eks.md
- internal/commands/ls/ls.go
Better comparison logic in history entries, ignores the protocol flag
Also adds shorthand -o flag to ls command
Fixes #149
> fix: duplicate history entries

- pkg/aws/config.go
- pkg/aws/identifer.go
- pkg/plugins/discovery/aws/config.go
- pkg/plugins/discovery/aws/provider.go
- pkg/plugins/identity/saml/saml.go
- pkg/plugins/identity/saml/sp/aws/provider.go
- pkg/plugins/identity/saml/sp/aws/resolver.go
- pkg/plugins/identity/saml/sp/aws/store.go
- pkg/plugins/identity/saml/sp/types.go
This changes the AWS profile to be generated from a hash of the PrincipleARN. This is so it is re-used.
Also, the cluster/context/username have been shortened in the kubeconfig
Fixes #
> feat: Profile name change

- internal/app/list.go
- pkg/history/history.go
- pkg/history/store.go
- pkg/history/store_test.go
Display the results sorted by `LastUsed` timestamp with the most recently used first when using `kconnect ls` command
Fixes #156
> feat: sort by last used timestamp for ls command

- Dockerfile
- docs/book/src/installation.md
When running in docker user where experiencing a permission denied error when running kconnect for the first time.
The installation instructions have also neeb updated.
Fixes #
> fix: running in docker resulted in permission denied

- .github/workflows/titlecheck.yml
Disable the WIP check until th eupstream bug is fixed.
Fixes #180
> chore: disable wip check

- go.sum
- internal/app/to.go
- pkg/plugins/identity/saml/sp/aws/provider.go
- pkg/plugins/identity/saml/sp/aws/resolver.go
- pkg/utils/filter.go
- pkg/utils/utils_test.go
Allows wildcard filters in survey selections, such as history entry, region, and aws role selection
You can provide * or a space to separate a filter into subfilters
Only entries which match all subfilters will be shown e.g.
`? Select an AWS region 123 EKS  [Use arrows to move, type to filter]
> Account: account-1 (123456789) / EKS_Role1
Account: account-2 (123123123) / EKS_Role2`
Fixes #182
> feat: Filter wildcard

- api/v1alpha1/history_types.go
This changes the history id to be lower case. This is so its more consistent with other kubernetes cli tools like kubctl that uses lower case.
Fixes #190
> feat: history id is lower case

- docs/book/src/commands/use_aks.md
- pkg/plugins/discovery/azure/defaults.go
- pkg/plugins/discovery/azure/errors.go
- pkg/plugins/discovery/azure/provider.go
- pkg/plugins/discovery/azure/resolver.go
Allow users to specify a subscription by name. This will be better UX.
Fixes #191
> feat: specify subscription by name for AKS

- internal/app/to.go
The kconnect global config is applied to the configuration items when using the `to` command
Fixes #199
> fix: apply global config for the to command

- internal/app/use.go
The reconnect help text wasn't displaying correctly.
Fixes #198
> fix: show reconnect help text correctly

- .gitignore
- .golangci.yml
- api/v1alpha1/history_types.go
- docs/book/src/commands/use_aks.md
- hack/tools/go.mod
- internal/app/list.go
- internal/commands/version/version.go
- pkg/azure/client/client.go
- pkg/azure/identity/endpoints.go
- pkg/azure/identity/types.go
- pkg/errors/validation.go
- pkg/flags/unmarshal.go
- pkg/http/http_client.go
- pkg/plugins/discovery/azure/config.go
- pkg/plugins/discovery/azure/defaults.go
- pkg/plugins/discovery/azure/discover.go
- pkg/plugins/discovery/azure/get.go
- pkg/plugins/discovery/azure/provider.go
- pkg/plugins/discovery/azure/resolver.go
- pkg/provider/types.go
Adds a `--cluster-name` flag to the AKS provider so that you can use it to select a specific cluster in a subscription/resource group instead of having to use the `--cluster-id` which is less user friendly
Fixes #234
> feat: added cluster-name flag to AKS

- CONTRIBUTING.md
Change in sequence of steps in contributor guide
Changed the sequence of tests required for building the source code in contributor guide. 
We can also looking at the feasibility of downloading this module automatically if it is not present
Documentation improvement
> docs: change in sequence of steps in contributor guide

- internal/commands/root.go
An exception occured during version checking if there was no last version.
Fixes #255
> fix: version check fails when missing last version

- .goreleaser.yml
This removed the version number from the published file names for the .deb & .rpm packages. This is to make it easier to script the download of the latest version.
Fixes #260
> build: remove version numbers from deb/rpm package file names

- docs/book/src/SUMMARY.md
- docs/book/src/commands/config.md
- docs/book/src/commands/index.md
- internal/commands/config/config.go
- internal/commands/root.go
- internal/commands/use/use.go
This renames the `configure` command to `config` for consistency with kubectl. An alias has been added to so that `configure` can still be used.
Fixes #265
> feat: renamed configure command to config for consistency

- docs/book/src/commands/alias.md
- docs/book/src/commands/alias_add.md
- docs/book/src/commands/alias_ls.md
- docs/book/src/commands/alias_remove.md
- docs/book/src/commands/config.md
- docs/book/src/commands/index.md
- docs/book/src/commands/logout.md
- docs/book/src/commands/ls.md
- docs/book/src/commands/to.md
- docs/book/src/commands/use.md
- docs/book/src/commands/use_aks.md
- docs/book/src/commands/use_eks.md
- docs/book/src/commands/use_rancher.md
- docs/book/src/commands/version.md
- internal/app/config.go
- internal/commands/root.go
- internal/commands/use/use.go
- pkg/flags/flags.go
If not running in a terminal then --no-input is set automatically.
Added --no-input to disable interactivity and deprecated --non-interactive to make kconnect more consistent with other clis.
Fixes #267
> feat: detect if running in terminal and added --no-input

- go.mod
- internal/commands/alias/add.go
- internal/commands/alias/alias.go
- internal/commands/alias/ls.go
- internal/commands/alias/remove.go
- internal/commands/config/config.go
- internal/commands/logout/logout.go
- internal/commands/ls/ls.go
- internal/commands/root.go
- internal/commands/to/to.go
- internal/commands/use/use.go
- internal/commands/version/version.go
- pkg/plugins/discovery/aws/provider.go
- pkg/plugins/discovery/azure/provider.go
- pkg/plugins/discovery/rancher/provider.go
- pkg/utils/command.go
- pkg/utils/filter.go
Formats help messages correctly when running an a kubectl plugin
Fixes #225
> feat: kubectl plugin help messages

- docs/book/src/commands/history.md
- docs/book/src/commands/history_rm.md
- go.mod
- go.sum
- internal/app/config.go
- internal/app/history.go
- internal/commands/history/history.go
- internal/commands/history/rm.go
- pkg/history/store_test.go
Allows users to delete history entries
Fixes #283
> feat: add history rm command

- go.mod
- internal/commands/root.go
Change behavior of new version check to display a warning instead of erroring out (if there is a problem checking it)
Fixes #294
> feat: change version check error to warning

- .goreleaser.yml
- docs/book/src/commands/use_aks.md
- docs/book/src/getting-started.md
- docs/book/src/installation.md
- pkg/plugins/discovery/azure/config.go
- pkg/plugins/discovery/azure/defaults.go
- pkg/plugins/discovery/azure/discover.go
- pkg/plugins/discovery/azure/provider.go
- pkg/plugins/discovery/azure/types.go
- pkg/utils/prerequisites.go
This adds kubelogin to the kubeconfig generation for non-admin users.
**Still work in progress**
Fixes #281
> feat: adding kubelogin support to AKS provider

- internal/commands/alias/add.go
- internal/commands/alias/ls.go
- internal/commands/alias/remove.go
- internal/commands/config/config.go
- internal/commands/history/export.go
- internal/commands/history/import.go
- internal/commands/history/rm.go
- internal/commands/logout/logout.go
- internal/commands/ls/ls.go
- internal/commands/root.go
- internal/commands/use/use.go
- internal/helpers/common.go
- pkg/app/config.go
- pkg/app/to.go
- pkg/config/apply.go
There was issues with the peristsnet commands being.
Fixes #
> fix: root peristent commands not being used

- pkg/plugins/identity/rancher/activedirectory/activedirectory.go
After the recent factor there was an issue with the Rancher Active Directort plugin
Fixes #
> fix: panic as httpclient not peristed to provider

- pkg/prompt/prompt.go
Change the sensitive config item resolution to not report the value
Fixes #313
> fix: passwords in logs

- docs/book/src/commands/use_eks.md
- pkg/aws/resolve.go
- pkg/plugins/discovery/aws/provider.go
- pkg/utils/filter.go
- pkg/utils/utils_test.go
Changes eks region filter to use regex, allowing for a lot more flexibility in setting this in the kconnect config file
Fixes #368
> feat: aws region regex filter

- Dockerfile
- Dockerfile.alpine
- Dockerfile.deps
This PR will add a `USER` instruction to all of the `Dockerfiles`, such that the Docker images will not run as the `root` user.
This is considered a best practice, has been request, and is required by some users.
Fixes #380 
**Testing:**
I created a test image locally, and the changes work as expected:
```
% docker run --rm -it --entrypoint sh kconnect-deps:test
/app $ whoami
kconnect
```
Also, `kconnect` still runs as expected:
```
% docker run --rm -it --entrypoint sh kconnect-deps:test
/app $ kconnect config -f http://<url>
...
info	successfully imported configuration
/app $ kconnect use eks …
```
> feat: add user instruction to Dockerfiles

- .github/workflows/titlecheck.yml
- docs/book/src/installation.md
This PR is to hopefully fix this issue with the `titlecheck` Github Action, and update the `installation` doc to include the new minimum required `aws-iam-authenticator` version now that we updated the `apiVersion` within `kconnect`.
This is the error we are seeing whenever a PR gets opened by a forked repository:
`Error: Resource not accessible by integration`
[Example failed job message](https://github.com/fidelity/kconnect/runs/5540519833?check_suite_focus=true)
If the PR comes from within the `kconnect` repository, we will not see this error.
There is a closed issue within the Github Action that references this error message, but the Github issue redirects to two other links:
- https://github.com/aslafy-z/conventional-pr-title-action/issues/119 …
> fix(actions): switch action, and update installation doc

- .github/workflows/release-docs.yml
This PR will update the name of the Github Action that handles the releasing of the documentation. Currently, the Github Action name matches the Github Action that handles creating a release. Therefore, it is confusing to figure out which one is the correct Github Action. By changing the name of the Github Action, this should help avoid confusion and debugging.
Fixes #
> feat(actions): release-docs action name was the same as creating a release action

- scripts/install-kconnect.sh
Updates aws-iam-authenticator in install script to v0.5.5, which is now the minimum required version to work with kconnect
Fixes #
> chore: update aws-iam-authenticator version in install script

- .github/workflows/titlecheck.yml
This PR will hopefully fix this issue I have been noticing where there is a Github Action check that never completes.
I noticed with the newer PR title checker they only set the `context` if the Github Action fails, where the original PR title checker will always set the `context`:
- https://github.com/aslafy-z/conventional-pr-title-action/blob/da8f29a36764af935378bfe7e30ae4dcf692547a/src/index.js#L53
I also could not find anything online about removing, or cleaning up, this possible orphaned check. Therefore, I believe reverting back to the original PR title checker with the new `pull_request_target` Github Action event trigger will be best.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
> feat(actions): revert to old titlechecker in order to hopefully fix the orphaned context check

- .github/workflows/titlecheck.yml
Testing PR title checker action to see if it works now. None of the checks appear to be running, so going back to the new PR title checker.
Fixes #
> feat(actions): revert to new pr title checker since no checks are running now

- .github/workflows/titlecheck.yml
Testing PR action again.
Turns out Github Actions is having issues 🤦 
> **Edit:** Now that Github Actions are healthy, I am going to try the original PR title checker in order to fix that orphan context again.
Fixes #
> feat(actions): revert to original pr title action now that Github Actions are healthy again

- .github/workflows/titlecheck.yml
Testing PR titlechecker Github Action.
The `conventional-pr-title` context completes successfully, but now `PR title follows coventional commit` hangs around so reverting that change as well.
Starting to think in order to remove or change this we would need to create an entirely new workflow YAML, instead of reusing the `titlechecker.yaml` file.
Fixes #
> feat(actions): revert pr title checker action job name, and pin version

- docs/book/src/commands/use_eks.md
- pkg/aws/clients.go
- pkg/aws/identity.go
- pkg/aws/map.go
- pkg/aws/store.go
- pkg/plugins/discovery/aws/config.go
- pkg/plugins/discovery/aws/provider.go
- pkg/plugins/identity/aws/iam/provider.go
- pkg/plugins/identity/saml/saml.go
- pkg/plugins/identity/saml/sp/aws/provider.go
Users can now specify where to store AWS shared credentials file, instead of the default location at $HOME/.aws/credentials
The aws-iam-authenticator section in kubeconfig will also be updated to reflect this new location
Fixes #388
> feat: allow setting of aws shared credentials file location

- scripts/install-kconnect.sh
This PR should fix the issue of the `install-kconnect.sh` not being able to run with no tty for linux users. Instead, Linux users will receive the install script needed to be executed in order to install the Azure CLI. Similar to Windows users with the *.msi file.
Fixes #436
> fix(scripts): update install-kconnect.sh to not automatically run azure cli install script for linux

- CONTRIBUTING.md
Signed-off-by: Brian Warner <brian.warner2@fmr.com>
Fidelity is updating and standardizing our GitHub presence. This PR adds various guidelines from the default contributor guide.
N/A (governance related PR)
> feat: Update contributor guide to include language from the template

- Dockerfile
- Dockerfile.alpine
- Dockerfile.deps
**What this PR does / why we need it**: We need to upgrade the base image to alpine version 3.17 as 3.16 will be EOL in Fidelity.
> feat(images): upgrade alpine to 3.17

- Dockerfile.deps
This PR will upgrade the version of the Azure CLI image that is being used within the `Dockerfile.deps` file. This change is needed in order to upgrade the underlying `alpine` version to `3.17`, and might as well upgrade the Azure CLI version.
Fixes # OpenSSL 1.1.1 EOL on 9/11/2023
```
% docker run -it --rm --entrypoint bash mcr.microsoft.com/azure-cli:2.48.1
2042604ccd87:/# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.17.3
PRETTY_NAME="Alpine Linux v3.17"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
2042604ccd87:/# …
```
> feat(Docker): upgrade Azure CLI image

- .github/workflows/codeql-analysis.yml
- .github/workflows/docs-verify.yml
- .github/workflows/main.yml
- .github/workflows/release-docs.yml
- .github/workflows/release.yml
- .goreleaser.yml
This change will update needed changes to `goreleaser`. While trying to create a prerelease, the `goreleaser` failed: https://github.com/fidelity/kconnect/actions/runs/5615976944/job/15217371412#step:6:25
One issue was that we were using deprecated fields: https://goreleaser.com/deprecations/#archivesreplacements
The second issue is that GitHub Actions are going to remove support for `node12`: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
Therefore, we needed to upgrade the following GitHub Actions:
- https://github.com/docker/setup-qemu-action/releases/tag/v2.0.0
- https://github.com/actions/setup-go/releases/tag/v3.0.0
- …
> fix(actions): upgrade actions to use node16, and resolve goreleaser deprecations

- .github/workflows/release.yml
There appears to be some modules that require Go 1.20 during the GoReleaser workflow. This will hopefully fix the error message seeing within the GoReleaser workflow.
Fixes # [goreleaser 60](https://github.com/fidelity/kconnect/actions/runs/5617116378/job/15220664928)
***This branch can be deleted once it is merged.***
> fix(actions): upgrade the goreleaser go version

- .github/workflows/release.yml
This PR will fix the issue within the `goreleaser` GitHub Action:
```
⨯ release failed after 0s                  error=hook failed: go mod download: exit status 2; output: go: unknown subcommand "mod"
Run 'go help' for usage.
```
Turns out there is a behavior with YAML where if we provide a number the YAML will be parsed to ignore the trailing zero. Therefore, instead of using `Go1.20`, the GitHub Action was using `Go1.2`:
```
Successfully set up Go version 1.2
##[add-matcher]/home/runner/work/_actions/actions/setup-go/v3/matchers.json
##[debug]Added matchers: 'go'. Problem matchers scan action output for known warning or error strings and report these inline.
go version go1.2.2 linux/amd64
```
I was able to confirm that other users ran into the …
> feat(actions): update the go-version field to use a string instead of a number

- .goreleaser.yml
This will hopefully fix the naming of the different asset names within the Release section. The asset names are missing the OS. Also, hopefully the extra period will disappear. Currently, I am not sure where that extra period comes from.
```
kconnect_macos_.arm64.tar.gz
kconnect__.amd64.apk
kconnect__.amd64.deb
kconnect__.amd64.rpm
kconnect__.amd64.tar.gz
kconnect__.amd64.zip
kconnect__.arm64.apk
kconnect__.arm64.deb
kconnect__.arm64.rpm
kconnect__.arm64.tar.gz
```
Fixes #
***This branch can be deleted once it is merged.***
> feat(actions): update asset name

- pkg/plugins/identity/saml/sp/aws/provider.go
This PR will enable `regional` endpoint resolving, such that when we call AWS STS we will use the specific region that the user is attempting to connect to instead of the global AWS STS endpoint `https://sts.amazonaws.com`.
Reference: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html
Locally built `kconnect` with `make ci`, and was able to connect to a cluster:
```
% ./kconnect use eks
info    kconnect - the Kubernetes Connection Manager CLI        {"version": ""}
info    authenticating user     {"app": "kconnect", "provider": "saml"}
? Select an AWS region eu-central-1
? Username: <username>
? Password: <password>
? Select AWS role Account: <AWS-role>
info    checking svc.Endpoint regional -> …
```
> feat(aws): enable regional endpoint resolving for STS

- pkg/app/to.go
- pkg/history/store.go
This makes the `to` sub command respect the -k flag. It also makes `to -` respect the config file path stored in the history entry.
It will leave the history entry untouched, meaning the next call to `to` will revert back to the config file passed when creating the entry.
I had to prevent the history entries from comparing on the config file field, as doing so leads to the duplication of entries when using -k, which then in turn breaks the alias until the file is edited by hand.
With the below change the config file is not considered during history entry comparisons.
Fixes #352
Replaces PR #409 …
> fix: Respecting -k parameter in "kconnect to"

- Dockerfile.deps
- docs/book/src/commands/use.md
- docs/book/src/commands/use_oidc.md
- internal/commands/use/use.go
- pkg/oidc/config.go
- pkg/oidc/identity.go
- pkg/plugins/discovery/oidc/config.go
- pkg/plugins/discovery/oidc/discover.go
- pkg/plugins/discovery/oidc/get.go
- pkg/plugins/discovery/oidc/provider.go
- pkg/plugins/discovery/oidc/resolver.go
- pkg/plugins/identity/oidc/provider.go
- pkg/plugins/identity/plugins.go
- pkg/utils/prerequisites.go
- scripts/install-kconnect.sh
User start to use EKS, but use Azure AD and OIDC protocol, for authentication and authorization, which current Kconnect doesn't support.
**Major Changes**:
**1.** Added new command, kconnect use oidc
**2.** The support for OIDC, is through kubectl extension, and authentication and authorization will happened when user executing kubectl commands, so just generate kubeconfig file and set contexts. No Authentication and Discovery happened.
**3.** New feature: Read config from https server, and combine them together with default config file and command parameters.
**Which issue(s) this PR fixes** 
Fixes #554
> feat: add use oidc cmd

- docs/book/src/commands/use_eks.md
- pkg/plugins/discovery/aws/provider.go
- pkg/plugins/identity/saml/saml.go
- pkg/plugins/identity/saml/sp/aws/provider.go
This PR will allow EKS users to leverage cross-account support. This means the feature will allow users to provide a new flag called `--assume-role-arn`, `kconnect` will login will the main credentials, and then switch to a different AWS IAM role within another AWS Account.
This is helpful for users who want to be part of a single AD group in a central AWS account, which then assumes and gives access to any EKS cluster instead of having to be in several different AD groups for each AWS account.
Fixes #
**Testing**:
- `make ci` completed successfully
- was able to connect to a cluster, and assume …
> feat(eks): cross-account support

- docs/proposals/20200607-initial-design.md
Removed a duplicate word (choosing choosing) in design document. 
Fixes #598
> docs: fixed duplicate word in design document

- Dockerfile.deps
- Makefile
This change will upgrade the various dependencies within the `Dockerfile.deps` file, and update some deprecated flags within `goreleaser`. We need this change, because a user requested that we upgrade the `Helm` version to at least `3.13`.
> Request to support helm version 3.13 at least in kconnect docker image
> The older Helm lacks the feature (--dry-run=server mode specifically)
Fixes #
***This branch can be deleted once it is merged.***
> feat(Dockerfile): upgrade deps image

- .github/workflows/release.yml
- .github/workflows/titlecheck.yml
- .goreleaser.yml
This change is needed to fix the deprecated message `'DEPRECATED: brews.folder should not be used anymore, check https://goreleaser.com/deprecations#brewsfolder for more info'`, and to fix the issue `'unknown directive: toolchain'` which is introduced, because we upgraded the source code to use go1.22, but not the GitHub Action
Fixes # https://github.com/fidelity/kconnect/actions/runs/8986941097/job/24684255990
Enabled the `pull_request` trigger to test the GitHub action changes before merging to the `main` branch, and the GitHub action changes completed successfully:
***This branch can be …
> feat(actions): upgrade the goreleaser step to version 5, and setup-go version to 1.22

- .goreleaser.yml
This change is needed to prevent the prerelease version from being the latest version. The `goreleaser` GitHub action unfortunately does not enable this setting by default, https://github.com/goreleaser/goreleaser/blob/main/internal/pipe/git/git.go#L311. Therefore, we need to enable this setting because more often than not the prerelease tag is the same commit as the release tag.
[For more information about the git.prerelease_suffix setting](https://goreleaser.com/customization/git/?h=prerelease_suffix)
Fixes # the `goreleaser` GitHub action from getting the wrong version:
```
• getting and …
```
> feat(actions): add git.prerelease_suffix within .goreleaser.yaml

- pkg/plugins/identity/azure/aad/aad.go
This change will update the Azure AAD protocol to try an interactive login if the non-interactive login fails for any reason. If the interactive login also fails, then we return an error. We have noticed that some users receive different error messages when attempting to do a non-interactive login, so this change will hopefully cover those other error messages.
Fixes #
Users were seeing the following error message:
```
C:> az login -u XXX -p XXX
(pii). Status: Response_Status.Status_InteractionRequired, Error code: 3399614476, Tag: 557973645
Please explicitly log in with:
az login
```
Instead of …
> feat(aks): update the aad protocal to try interactive login no matter the failure

- Dockerfile
- Dockerfile.alpine
- Dockerfile.deps
- go.mod
- This change will upgrade the various binaries mentioned within the three different Dockerfiles. We need to keep the binaries up to date to leverage either security fixes, or new features
- Also, a bit of organizational change, we grouped all of the indirect dependencies to their own require block in the go.mod file.
Fixes # Need to upgrade dependencies.
> feat(Dockerfiles): upgrade dependencies within the Dockerfiles

- Dockerfile.deps
This change will avoid using the `Microsoft Azure CLI` Docker image, because the newer versions contain `Azure Linux` operating system instead of `Alpine`. This change in operating system can cause issues for users building on top of this image. Therefore introducing a breaking change, which I think we should try to avoid.
I used this GitHub issue for reference: https://github.com/Azure/azure-cli/issues/19591
Fixes # The new `mcr.microsoft.com/azure-cli:2.67.0` Docker image has migrated to using `Azure Linx` instead of `Alpine` for the underlying operating system: …
> feat(Dockerfile.deps): switch to python:alpine base image

- .github/workflows/titlecheck.yml
This change will migrate the `titlecheck` GitHub workflow from `aslafy-z/conventional-pr-title-action@v3.2.0` to `amannn/action-semantic-pull-request@v5`, because the GitHub Action `aslafy-z/conventional-pr-title-action` has been archived, and will no longer receive updates. Therefore, we should look to use an alternative GitHub Action that is being actively worked on. The archive notice on the GitHub repository mentions this `amannn/action-semantic-pull-request` GitHub Action as an alternative with mostly similar functionalities, and it is recommended.
Fixes # …
> feat(actions): migrate titlecheck workflow to amannn/action-semantic-pull-request@v5

- .github/workflows/release-docs.yml
- .github/workflows/release.yml
- .github/workflows/titlecheck.yml
- .goreleaser.yml
- Dockerfile
- Dockerfile.alpine
- Dockerfile.deps
- Makefile
This change will upgrade the dependencies referenced within the different `Dockerfiles`, as well as update the `goreleaser` configuration yaml file. There were some deprecated fields, and have been updated to the new field, or syntax format.
This change will also add a missing package `libudev-dev` to resolve the issue with the `build-docs` GitHub Action. The `libudev-dev` package is required by the `github.com/bearsh/hid` package, which is indirectly referenced by the `github.com/versent/saml2aws/v2` package.
Fixes #
https://github.com/fidelity/kconnect/actions/runs/16240710616/job/45856725583 …
> feat(deps): upgrade dependencies in Dockerfiles, and update goreleaser config
