.github/ISSUE_TEMPLATE/feature_request.md
Adds the feature request template
Relates #2
=> docs: added feature request template

.github/workflows/main.yml
Added initial CI workflow that checks the PR title follows
the semantic commit naming. Also added a WIP check
Relates To: #15
=> chore: added CI GitHub Actions workflow

docs/README.md, docs/proposals/20200607-initial-design.md, docs/proposals/20200630-cli-ux.md, docs/proposals/YYYYMMDD-template.md
Added a new proposal for the UX CLI based on notes from @rajarajanpsj.
Also added a template and changed docs folder structure.
Fixes #
=> docs: added cli ux proposal

.github/workflows/release.yml, go.mod, go.sum
Added a new GitHub Actions workflow that will invoke GoReleaser
when a new tag is pushed.
Relates to #16
=> build: added goreleaser github actions

docs/proposals/20200630-cli-ux.md
Started to update the IX doc with samples for AKS.
Fixes #
=> docs: updated CLI ux doc with AKS samples

.github/workflows/main.yml, .github/workflows/titlecheck.yml
A small refactor to the github actions workflows
Fixes #
=> refactor: changed the github actions workflows

.github/workflows/main.yml
=> refactor: changed the jobs for the main CI workflow

.github/workflows/titlecheck.yml
=> refactor: conventional commit check requirs wip to pass

.github/workflows/main.yml, .github/workflows/release.yml, .gitmodules, .golangci.yml, go.mod, go.sum, pkg/plugins/identity/saml/saml.go, pkg/plugins/identity/saml/sp/aws/provider.go, pkg/provider/flags.go, pkg/provider/types.go
Minor changes to enabled Ping as an Idp to work correctly.
Fixes #
=> fix: changes to allow ping to work

.goreleaser.yml
Adding homebrew to goreleaser
Fixes #
=> build: adding homebrew publishing

.goreleaser.yml
=> chore: added formula folder to goreleaser

.github/workflows/release.yml
=> chore: updated release worksflow with secret name

CONTRIBUTING.md, README.md
The readme has been updated with details of installation and very basic getting started. Also a new basic contributing guide has been added.
Fixes #4, #6
=> docs: updated readme and added contributing guide

.github/workflows/release.yml, .goreleaser.yml
=> feat: adding snap publishing

.github/workflows/scan.yaml
Added a GHA workflow to use the synk cli for scanning
Fixes #70
=> chore: added a synk scan github actions workflow

docs/proposals/20200827-history.md
Created a proposal to add history functionality to kconnect
Fixes #
=> docs: history support in kconnect proposal

.github/workflows/release.yml, .goreleaser.yml
Disabling snap due to issues with approval in the store
Fixes #
=> chore: disable snap publishing

.goreleaser.yml, Dockerfile
=> build: adding docker goreleaser support

.github/workflows/release.yml, .goreleaser.yml
=> fix: added docker login to GH actions

.goreleaser.yml
=> fix: changing back to github packages

.github/workflows/release.yml, internal/commands/use/use.go
=> feat: changed to always set the current context by default

.github/workflows/release.yml
=> feat: changed the docker login address

.goreleaser.yml, internal/app/config.go, internal/app/list.go, internal/app/to.go, internal/app/use.go, internal/commands/configure/configure.go, internal/commands/ls/ls.go, internal/commands/root.go, internal/commands/to/to.go, internal/commands/use/use.go, pkg/plugins/discovery/aws/provider.go, pkg/plugins/identity/saml/saml.go, pkg/provider/config.go
Various fixes from the 0.1.0-rc.2 testing.
Fixes #92 
Fixes #93 
Fixes #94
=> fix: capitalization in usage, default log level and app folder

internal/app/configure.go, internal/commands/root.go
=> chore: output version to log on start

.github/workflows/release.yml, .goreleaser.yml, internal/app/configure.go, internal/commands/configure/configure.go
To follow the convention that users expect we should use `-f` instead of `-s`
Fixes #99
=> fix: import configuration uses -f

.github/workflows/release.yml, .goreleaser.yml
Change to the snapcraft publishing based on feedback
Relates #61
=> feat: add snapcraft publishing

pkg/plugins/discovery/aws/provider.go, pkg/plugins/identity/saml/sp/aws/resolver.go
=> feat: add region filter

docs/book/src/getting-started.md
Add docs on setting env vars based on flag names
=> docs: setting env vars based on flag names

pkg/plugins/discovery/aws/provider.go, pkg/plugins/identity/saml/sp/aws/provider.go
=> fix: role-filter was not being used

CONTRIBUTING.md
=> docs: update contributing docs with submodule command

.github/workflows/codeql-analysis.yml
This will enable the code quality checks for Go
Fixes #129
=> chore: enable code quality analysis

.github/workflows/release.yml, .goreleaser.yml
Publish the images for kconnect to docker hub
Fixes #128
=> feat: change to publishing images to docker hub

docs/proposals/20200630-cli-ux.md
The proposal docs had reference to a URL that doesn't exist. This has been changed in case its misleading
Fixes #111
=> chore: updated url in proposal as its misleading

internal/commands/root.go
=> chore: remove redundant code from root cmd

internal/app/use.go
If no alias is specified using `--alias` it will ask if you want to set an alias. This only applies to interactive mode.
Fixes #145
=> feat: prompt for alias in interactive mode

.github/workflows/release.yml, .goreleaser.yml
=> chore: removing snapcraft publishing as its not accepted

Dockerfile
=> chore: added user to Dockerfile

Dockerfile
=> chore: changed dockerfile to use distroless

.goreleaser.yml
=> chore: disable docker published and make draft

.goreleaser.yml, Dockerfile, README.md, docs/book/src/getting-started.md, docs/book/src/installation.md, internal/commands/root.go
This adds Docker Hub publishing back into the release. Also ARM compilation has been added.
Fixes #128 
Fixes #161
=> feat: docker hub publishing and arm builds

.goreleaser.yml
=> chore: removed the draft status

docs/book/src/commands/use_eks.md, internal/app/config.go, internal/app/to.go, internal/app/use.go, internal/commands/use/use.go
Fixes bug of namespace not being used in "to" command
Fixes #170
=> fix: Namespace not stored

docs/book/src/SUMMARY.md, docs/book/src/commands/alias.md, docs/book/src/commands/alias_add.md, docs/book/src/commands/alias_ls.md, docs/book/src/commands/alias_remove.md, docs/book/src/commands/configure.md, docs/book/src/commands/index.md, docs/book/src/commands/ls.md, docs/book/src/commands/to.md, docs/book/src/commands/use.md, docs/book/src/commands/use_eks.md, docs/book/src/commands/version.md, internal/commands/to/to.go, tools/cmddocsgen/cmddocsgen.go
The generated docs contain a comment mentioned that they are autogenerated. The docs have also been regenerated.
Fixes #175
=> chore: added auto generation comment and regenerated docs

README.md, docs/book/src/SUMMARY.md, docs/book/src/release.md
Added documentation that covers how we do a release.
Fixes #
=> docs: release documentation

docs/book/src/SUMMARY.md
=> chore: added missing references to aks docs

pkg/config/configuration.go
Creates .kconnect on startup
Fixes #184
=> fix: create .kconnect dir

.goreleaser.yml
Fixed a couple of issues reported by brew-bot of the fidelity tap with the kconnect brew
Fixes #205
=> fix: brew bot issues

pkg/plugins/identity/saml/sp/aws/provider.go
The `--roler-filter` flag wasn't working as expected for the SAML provider
Fixes #230
=> fix: role filter not working in saml provider

Makefile
Added a makefile target for easy building cross platform.
Fixes #
=> chore: added cross compile target

pkg/aws/map.go
There was an issue with the region being propagated in the AWS identity
Fixes #238
=> fix: region wasn't being propagated

.github/dependabot.yml
=> chore: added dependabot config for the tools

internal/commands/use/use.go
This fixes an issue that occurs when using the default identity provider.
Fixes #263
=> fix: default identity provider error

.goreleaser.yml, Dockerfile, Dockerfile.alpine
Adds an additional published container image based on alpine.
Fixes #268
=> feat: added publishing of an alpine based container image

docs/book/src/installation.md, go.mod, go.sum, internal/commands/root.go, internal/commands/use/use.go, pkg/aws/resolve.go, pkg/plugins/discovery/aws/provider.go, pkg/plugins/discovery/azure/provider.go, pkg/plugins/discovery/rancher/provider.go, pkg/provider/types.go, pkg/utils/prerequisites.go
Add prereq checks on kconnect run
Fixes #222 
Fixes #223
=> feat: Prereq checks

docs/book/src/commands/ls.md, internal/commands/ls/ls.go
A small typo reported by a user of kconnect
Fixes #
=> chore: correcting typo

docs/book/src/commands/history.md, docs/book/src/commands/history_export.md, docs/book/src/commands/history_import.md, docs/book/src/commands/index.md, go.mod, go.sum, internal/app/config.go, internal/app/history.go, internal/commands/history/export.go, internal/commands/history/history.go, internal/commands/history/import.go, internal/commands/root.go, pkg/flags/flags.go, pkg/flags/flags_test.go, pkg/history/filter.go, pkg/history/filter_test.go, pkg/history/history.go, pkg/history/store.go, pkg/history/store_test.go, pkg/utils/utils_test.go
Allows users to share history using import + export commands
Fixes #229
=> feat: history import + export commands

docs/book/src/commands/config.md, internal/commands/config/config.go, pkg/app/configure.go, pkg/http/http_client.go, pkg/http/types.go
Allows users to pass username and password when running config command
Fixes #293
=> feat: Config auth 2

pkg/app/to.go
Issue with the `to` command
Fixes #
=> fix: providers the wrong way around

.goreleaser.yml, Dockerfile.deps
This adds a new container image that has the kconnect dependencies included. It also updates the release process to include the containers.
Fixes #311
=> feat: added docker image with dependencies included

scripts/install-kconnect.sh
Install script was not working for many users
Fixes #327
=> fix: install script fixes

scripts/install-kconnect.sh
add kubelogin to install script
remove dpkg dependency
Fixes #328
=> feat: add kubelogin to install script

.golangci.yml, pkg/azure/identity/client.go, pkg/azure/identity/types.go
Fixes an issue where certain characters in a password or username prevented "use aks" from working
Fixes #332
=> fix: aks special char fix

pkg/azure/identity/endpoints.go
Signed-off-by: aido123 <adrianhynes@gmail.com>
Adding upstream fix which removes spn from aud claim. 
Ref: https://github.com/kubernetes/kubernetes/issues/86410
Fixes # https://github.com/fidelity/kconnect/issues/345
=> feat: Adding upstream fix which removes spn from aud claim.

pkg/utils/filter.go
=> feat: case insensitive when filtering

.goreleaser.yml
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
Fixes #357
=> Add maintainer for RPM

.goreleaser.yml
Fixes goreleaser issue
Fixes #
=> fix: goreleaser fix

.gitignore, .krew.yaml
Update the `.krew.yaml` to include the new `darwin/arm64`, and remove the `linux/arm` binary.
Fixes #
=> feat: remove linux/arm, and add new darwin/arm64

scripts/install-kconnect.sh
Fixes issue with install script 
Fixes #
=> fix: download aws-iam-authenticator from github

docs/book/src/installation.md
**What this PR does / why we need it**: Updating installation docs
=> fix: updating installation docs

Dockerfile, Dockerfile.alpine, Dockerfile.deps
This PR will upgrade the current `alpine` version of `3.14` to `alpine:3.16`. This is needed in order to resolve various detected vulnerabilities.
Fixes #
=> feat(images): upgrade alpine to 3.16 to resolve vulnerabilities

docs/book/src/commands/use.md, internal/commands/use/use.go
This is an update to the document to clarify that interactive mode with windows gitbash program is currently not supported due to dependencies on opensource
Fixes #439
=> fix:  updated use doc for issue 439

docs/proposals/20200607-initial-design.md
Removed duplicate word(get) in initial design documentation
Fixes #563
=> fix(documentation): updated the documentation #20200607-initial-design.md

docs/book/src/SUMMARY.md
Added oidc doc to the document site.
Fixes #
=> docs: add oidc doc link

docs/proposals/20200607-initial-design.md
Fixing broken document link
Fixes #584
=> docs: fixing broken docs links

docs/book/src/getting-started.md, docs/book/src/installation.md, docs/book/src/release.md
What this PR does / why we need it:
Updated .md files to correct typos.
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes https://github.com/fidelity/kconnect/issues/676
=> fix(docs): Typos corrected

Dockerfile, Dockerfile.alpine, Dockerfile.deps
This change will upgrade the various binaries mentioned within the three different `Dockerfiles`. We need to keep the binaries up to date to leverage either security fixes, or new features.
Fixes # Need to upgrade dependencies.
***This branch can be delete once it is merged.***
=> feat(deps): upgrade dependencies in Dockerfiles
